## **Before you start**

Make a copy of this Colab by clicking on File > Save a Copy in Drive

After making a copy, add your student id, last name, and first name to the title.

# Exercises Naive Bayes Classifier

## Naive Bayes - Example

Consider a dataset with 3 classes and 5 binary attributes. Let the arrays p_class and p_att_given_class be:

In [ ]:
import numpy as np

p_class = np.ones(3)/3
p_att_given_class = np.array([[0.72, 0.21, 0.89, 0.47, 0.64],[0.32, 0.82, 0.54, 0.82, 0.17],[0.76, 0.65, 0.74, 0.31, 0.75]])

print(p_class)
print()
print(p_att_given_class)


[0.33333333 0.33333333 0.33333333]

[[0.72 0.21 0.89 0.47 0.64]
 [0.32 0.82 0.54 0.82 0.17]
 [0.76 0.65 0.74 0.31 0.75]]


where p_class[i] represents the probability that an example belongs to class i and p_att_given_class[i,j] 
represents the probability that attribute j in an example of class i is equal to 1. 

What is the probability that for an example of class 2, attribute 0 is equal to 1?

In [ ]:
print(p_att_given_class[2,0])

0.76


What is the probability that for an example of class 1, attribute 4 is equal to 0?

In [ ]:
print(1-p_att_given_class[1,4])

0.83


How would the Naïve Bayes classifier classify example [1,1,1,0,0]? 

In [ ]:
def classify(x,pc,pac):
  p = pc 
  for i in range(x.shape[0]): #i = 3
    if x[i]==1:
      p = p* pac[:,i] 
    else:
      p = p*(1-pac[:,i])
  p = p/np.sum(p)
  print(p)
  return np.argmax(p)


In [ ]:
def classify_no_loops(x,pc,pac):
  p = x*pac + (1-x)*(1-pac)
  p = np.prod(p, axis=1)
  p = pc*p
  p = p/np.sum(p)
  print(p)
  return np.argmax(p)

In [ ]:
test_example = np.array([1,1,1,0,0])

classify(test_example,p_class,p_att_given_class)

[0.23361808 0.19261693 0.57376499]


2

In [ ]:
test_example = np.array([1,1,1,0,0])

classify_no_loops(test_example, p_class, p_att_given_class)


[0.23361808 0.19261693 0.57376499]


2

## Exercise 1

Write a program to classify the MNIST dataset using the Naive Bayes classifer. 

Read the dataset

In [ ]:
import tensorflow as tf
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
x_train = np.float32(x_train/255).reshape(x_train.shape[0],-1)
x_test = np.float32(x_test/255).reshape(x_test.shape[0],-1)

Create a new dataset using binary attributes as follows:

m = mean pixel value in x_train

x_train_binary[i,j]  =  1 if x_train[i,j] >m; otherwise x_train_binary[i,j] = 0

x_test_binary[i,j]  =  1 if x_test[i,j] >m; otherwise x_test_binary[i,j] = 0



In [ ]:
#mean pixel value of x_train
m = x_train.mean()

#make copies of the original tables
x_train_binary = np.copy(x_train)
x_test_binary = np.copy(x_test)

#1 if x_train[i,j] > m otherwise 0
x_train_binary[x_train_binary > m] = 1.0
x_train_binary[x_train_binary <= m] = 0.0

x_test_binary[x_test_binary > m] = 1.0
x_test_binary[x_test_binary <= m] = 0.0

print(x_test_binary.shape)

print("mean pixel value:  ", m)

print("mean train binary: ", x_train_binary.mean())
print("mean test binary:  ",x_test_binary.mean())


(10000, 784)
mean pixel value:   0.13066062
mean train binary:  0.16980651
mean test binary:   0.17136262


Compute class probabilities (p_class) from training data, where p_class[i] represents the probability that an example belongs to class i. You can estimate this by dividing the number of instances in your training dataset that belong to class i over the number of training examples.

In [ ]:
y_train_instance = np.copy(y_train)

#number of instances in your training dataset that belong to class i over the number of training examples.
p_class = y_train_instance[y_train_instance == 1] / y_train.size

print(np.count_nonzero(p_class))

6742


Compute conditional probabilities (p_att_given_class) from training data, where p_att_given_class[i,j] represents the probability that attribute j in an example of class i is equal to 1. You can estimate this by dividing the number of times attribute j is equal to 1 in training instances of class j over the number of training instances of class i

In [ ]:
print(x_train_binary.shape[0])
p_att_given_class = []


for i in range(x_train_binary.shape[0]):
   prob = (np.count_nonzero(x_train_binary[i])) / x_train_binary[i].size
  p_att_given_class.append(prob)


print(p_att_given_class)
print(len(p_att_given_class))

  



60000


KeyboardInterrupt: ignored

Classify test data - print accuracy and confusion matrix (feel free to use sklearn to print the accuracy and confusion matrix)




In [ ]:
# Your code here
import sklearn as sk
y_pred = classify_no_loops(x_test, p_class, p_att_given_class)

sk.metrics.confustion_matrix(y_test, y_pred)
sk.metrics.accuracy_score(y_test, y_pred)

ValueError: ignored

## Submission Instructions

1. File > Download .ipynb
2. Go to Blackboard, find the submission page, and upload the .ipynb file you just downloaded.